version: "3"
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/jijueapp
    image: app:jijueapp

    container_name: django_container
    env_file:
        - ./.env
  
    command: python3 manage.py runserver 0.0.0.0:8000
