name: CI
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CICD2_HOST }}
        username: ${{ secrets.CICD2_USERNAME }}
        key: ${{ secrets.CICD2_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
            # rm existing folder
            cd /apps/dockerApps/
            sudo rm -rf jijue
            # create a new folder
            sudo mkdir jijue
            # give permissions on the folder
            sudo chown cicd2:cicd2 jijue
            # clone the master branch from  the github
            cd jijue
            git clone -b main https://github.com/palladiumkenya/jijueApp-hiv-risk-assessment-site.git .
            # bring down existing docker image
            docker stop jijue
            # remove the image .
            docker rm -f jijue
            # create the image
            docker build -t jijue:latest .
            #bring up the image
            docker run -p 8900:8000 --name=jijue  jijue:latest
